#%RAML 1.0
title: api-user-v1
version: v1
protocols: [ HTTPS ]
mediaType: application/json

traits:
  Countable: !include common/traits/countable.raml
  Pageable: !include common/traits/pageable.raml
  Sortable: !include common/traits/sortable.raml
  Errorable: !include common/traits/errorable.raml
  Trackable: !include common/traits/trackable.raml
  RequestCode: !include common/traits/request-code.raml

types:
  GetUsersResponse: !include /common/data-types/get-users-response.raml
  CreateUsersResponse: !include /common/data-types/create-users-response.raml
  CreateUsersRequest: !include /common/data-types/create-users-request.raml
  GetHealthResponse: !include /common/data-types/get-health-response.raml


/users:
  post:
    is:
      - Errorable
      - Trackable
      - RequestCode
    description: Create user/s
    body:
      application/json:
        type: CreateUsersRequest
        example: !include /examples/create-users-request.json
    responses:
      200:
        body:
          application/json:
            type: CreateUsersResponse
            example: !include /examples/create-users-response.json
  get:
    is:
      - Errorable
      - Trackable
      - RequestCode
    description: Get all users
    responses:
      200:
        body:
          application/json:
            type: GetUsersResponse
            example: !include /examples/get-users-response.json
  /{username}:
    get:
      is:
        - Errorable
        - Trackable
        - RequestCode
      description: Get user by username
      responses:
        200:
          body:
            application/json:
              type: GetUsersResponse
              example: !include /examples/get-users-response.json
/health:
  get:
    is:
      - Errorable
      - Trackable
      - RequestCode
    description: Get API health
    responses:
      200:
        body:
          application/json:
            type: GetHealthResponse
            example: !include /examples/get-health-response.json